'use strict';
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const { URL } = require('node:url');
const { readDb, writeDb } = require('./lib/store');

const PUBLIC_DIR = path.join(__dirname, 'public');
const SESSION_SECRET = process.env.SESSION_SECRET || 'development-only-change-me';
const GITHUB_CLIENT_ID = process.env.GITHUB_CLIENT_ID;
const GITHUB_REDIRECT_URI = process.env.GITHUB_REDIRECT_URI || 'http://localhost:3000/api/auth/github/callback';
const empty = () => ({ users: [], assessments: [] });
function json(res, status, body) { res.statusCode = status; res.setHeader('Content-Type', 'application/json; charset=utf-8'); res.setHeader('Cache-Control', 'no-store'); res.end(JSON.stringify(body)); }
async function body(req) { if (req.body && typeof req.body === 'object') return req.body; return new Promise((resolve, reject) => { let raw = ''; req.on('data', part => { raw += part; if (raw.length > 1e6) reject(new Error('Payload too large')); }); req.on('end', () => { try { resolve(raw ? JSON.parse(raw) : {}); } catch { reject(new Error('Invalid JSON')); } }); }); }
function hashPassword(password, salt = crypto.randomBytes(16).toString('hex')) { return new Promise((resolve, reject) => crypto.scrypt(password, salt, 64, (error, value) => error ? reject(error) : resolve(`${salt}:${value.toString('hex')}`))); }
async function verifyPassword(password, stored) { const [salt, saved] = stored.split(':'); const hash = (await hashPassword(password, salt)).split(':')[1]; return hash.length === saved.length && crypto.timingSafeEqual(Buffer.from(hash, 'hex'), Buffer.from(saved, 'hex')); }
function tokenFor(user) { const payload = Buffer.from(JSON.stringify({ id: user.id, exp: Date.now() + 604800000 })).toString('base64url'); const signature = crypto.createHmac('sha256', SESSION_SECRET).update(payload).digest('base64url'); return `${payload}.${signature}`; }
async function currentUser(req) { const [payload, signature] = (req.headers.authorization || '').replace(/^Bearer\s+/i, '').split('.'); const expected = payload ? crypto.createHmac('sha256', SESSION_SECRET).update(payload).digest('base64url') : ''; if (!payload || !signature || signature.length !== expected.length || !crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) return null; try { const decoded = JSON.parse(Buffer.from(payload, 'base64url')); if (decoded.exp <= Date.now()) return null; return (await readDb()).users.find(user => user.id === decoded.id) || null; } catch { return null; } }
function publicUser(user) { return { id: user.id, email: user.email, name: user.name || user.email.split('@')[0], github: user.github || null }; }
async function auth(req, res) { const user = await currentUser(req); if (!user) json(res, 401, { error: 'Please sign in to continue.' }); return user; }
function serveStatic(res, filename) { const safe = path.normalize(filename).replace(/^\.\.(?:[/\\]|$)/, ''); const fullPath = path.join(PUBLIC_DIR, safe || 'index.html'); if (!fullPath.startsWith(PUBLIC_DIR) || !fs.existsSync(fullPath)) return json(res, 404, { error: 'Not found' }); const type = fullPath.endsWith('.html') ? 'text/html' : fullPath.endsWith('.css') ? 'text/css' : fullPath.endsWith('.js') ? 'text/javascript' : 'application/octet-stream'; res.setHeader('Content-Type', `${type}; charset=utf-8`); fs.createReadStream(fullPath).pipe(res); }
async function handler(req, res) {
  const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`); const route = url.pathname;
  try {
    if (req.method === 'POST' && route === '/api/auth/register') { const { email, password, name = '' } = await body(req); if (!/^\S+@\S+\.\S+$/.test(email || '') || !password || password.length < 8) return json(res, 400, { error: 'Use a valid email and a password of at least 8 characters.' }); const db = await readDb(); if (db.users.some(user => user.email === email.toLowerCase())) return json(res, 409, { error: 'An account with this email already exists.' }); const user = { id: crypto.randomUUID(), email: email.toLowerCase(), name: String(name).slice(0, 80), passwordHash: await hashPassword(password), createdAt: new Date().toISOString() }; db.users.push(user); await writeDb(db); return json(res, 201, { token: tokenFor(user), user: publicUser(user) }); }
    if (req.method === 'POST' && route === '/api/auth/login') { const { email, password } = await body(req); const user = (await readDb()).users.find(item => item.email === String(email).toLowerCase()); if (!user || !await verifyPassword(password || '', user.passwordHash)) return json(res, 401, { error: 'Email or password is incorrect.' }); return json(res, 200, { token: tokenFor(user), user: publicUser(user) }); }
    if (req.method === 'GET' && route === '/api/me') { const user = await auth(req, res); if (user) json(res, 200, { user: publicUser(user) }); return; }
    if (req.method === 'PATCH' && route === '/api/profile/github') { const user = await auth(req, res); if (!user) return; const { github } = await body(req); if (!/^https:\/\/(www\.)?github\.com\/[A-Za-z0-9-]+\/?$/.test(github || '')) return json(res, 400, { error: 'Enter a public GitHub profile URL.' }); const db = await readDb(); Object.assign(db.users.find(item => item.id === user.id), { github }); await writeDb(db); return json(res, 200, { user: publicUser(await currentUser(req)) }); }
    if (req.method === 'POST' && route === '/api/assessments') { const user = await auth(req, res); if (!user) return; const { repo, answers } = await body(req); if (!/^https:\/\/(www\.)?github\.com\/.+\/.+/.test(repo || '') || !Array.isArray(answers) || answers.length !== 4) return json(res, 400, { error: 'Provide a repository and all four answers.' }); const score = Math.min(100, answers.reduce((total, answer) => total + (String(answer).trim().length >= 50 ? 25 : String(answer).trim().length >= 20 ? 15 : 5), 0)); const assessment = { id: crypto.randomUUID(), userId: user.id, repo, answers: answers.map(answer => String(answer).trim()), score, certificateId: `PRF-${crypto.randomUUID().slice(0, 8).toUpperCase()}`, createdAt: new Date().toISOString() }; const db = await readDb(); db.assessments.push(assessment); await writeDb(db); return json(res, 201, { assessment }); }
    if (req.method === 'GET' && route === '/api/assessments/latest') { const user = await auth(req, res); if (!user) return; const assessment = (await readDb()).assessments.filter(item => item.userId === user.id).at(-1) || null; return json(res, 200, { assessment }); }
    if (req.method === 'GET' && route === '/api/auth/github') { if (!GITHUB_CLIENT_ID) return json(res, 503, { error: 'GitHub OAuth is not configured. Add GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET.' }); const state = crypto.randomBytes(18).toString('hex'); res.writeHead(302, { 'Set-Cookie': `proof_oauth_state=${state}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=600`, Location: `https://github.com/login/oauth/authorize?client_id=${GITHUB_CLIENT_ID}&redirect_uri=${encodeURIComponent(GITHUB_REDIRECT_URI)}&scope=read:user&state=${state}` }); return res.end(); }
    if (req.method === 'GET' && route === '/api/auth/github/callback') return json(res, 501, { error: 'Finish GitHub OAuth token exchange before enabling this production callback.' });
    if (!route.startsWith('/api/') && req.method === 'GET') return serveStatic(res, route === '/' ? 'index.html' : route); return json(res, 404, { error: 'Not found' });
  } catch (error) { console.error(error); json(res, error.message === 'Invalid JSON' ? 400 : 500, { error: 'Something went wrong. Please try again.' }); }
}
module.exports = { handler, hashPassword, verifyPassword, tokenFor, empty };
